[package]
name    = "query-events"
version = "0.1.0"
edition.workspace = true

[dependencies]
tendermint.workspace = true
tendermint-rpc = { workspace = true, features = ["http-client"] }

clap               = { workspace = true, features = ["derive"] }
futures.workspace = true
itertools.workspace = true
tokio              = { workspace = true, features = ["full"] }
tracing.workspace = true           
tracing-subscriber = { workspace = true, features = ["env-filter"] }

