[package]
name       = "ibc-integration-test"
version    = "0.22.0"
edition.workspace = true
license.workspace = true
readme     = "README.md"
keywords   = ["blockchain", "consensus", "cosmos", "ibc", "tendermint"]
homepage.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = """
  Integration tests for IBC Relayer
"""

[dependencies]
ibc-relayer-types  = { path = "../../crates/relayer-types" }
ibc-relayer        = { path = "../../crates/relayer" }
ibc-test-framework = { path = "../test-framework" }

http.workspace = true
prost.workspace = true
serde_json.workspace = true
time.workspace = true
toml.workspace = true
tonic = { workspace = true, features = ["tls", "tls-roots"] }
serde.workspace = true

[features]
default = []
example = []
manual = []
ordered = []
ica = []
ics29-fee = []
experimental = []
mbt = []
forward-packet = []
ics31 = []

[[bin]]
name = "test_setup_with_binary_channel"
doc = true

[dev-dependencies]
tempfile.workspace = true
