[package]
name         = "ibc-relayer-rest"
version      = "0.22.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme       = "README.md"
keywords     = ["ibc", "rest", "api", "cosmos", "tendermint"]
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
description  = """
  Rust implementation of a RESTful API server for Hermes
"""

[dependencies]
ibc-relayer-types = { version = "0.22.0", path = "../relayer-types" }
ibc-relayer       = { version = "0.22.0", path = "../relayer" }

crossbeam-channel.workspace = true
rouille.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
toml.workspace = true
ureq.workspace = true
