[workspace]

resolver = "2"

members = [
    "crates/relayer",
    "crates/relayer-types",
    "crates/relayer-cli",
    "crates/relayer-rest",
    "crates/telemetry",
    "crates/chain-registry",
    "tools/integration-test",
    "tools/test-framework",
    "tools/check-guide",
    "tools/query-events",
]

[patch.crates-io]
# tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
# tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
# tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
# tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
# tendermint-light-client-verifier = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
# tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
# ibc-proto               = { git = "https://github.com/cosmos/ibc-proto-rs", branch = "main" }

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository   = "https://github.com/informalsystems/hermes"
homepage   = "https://hermes.informal.systems/"
rust-version = "1.65"
authors = ["Informal Systems <hello@informal.systems>"]

[workspace.dependencies]
ibc-proto         = "0.24.1"
tendermint-rpc    = "0.28.0"
async-trait = "0.1.64"
flex-error  = "0.4.4"
futures     = "0.3.26"
reqwest     = "0.11.13"
serde       = "1.0.149"
tokio       = "1.17.0"
subtle-encoding = "0.5"
humantime-serde = "1.1.1"
serde_derive = "1.0"
thiserror = "1.0.36"
toml = "0.5"
tracing = "0.1.36"
serde_json = "1"
bytes = "1.3.0"
prost = "0.11"
tonic = "0.8" 
crossbeam-channel = "0.5.5"
hex = "0.4"
bitcoin = "0.29.1"
tiny-bip39 = "1.0.0"
hdpath = "0.6.1"
sha2 = "0.10.6"
tiny-keccak = "2.0.2"
ripemd = "0.1.3"
bech32 = "0.9.1"
itertools = "0.10.5"
dirs-next = "2.0.0"
retry = "2.0.0"
async-stream = "0.3.3"
http = "0.2.8"
signature = "1.6.0"
anyhow = "1.0"
semver = "1.0"
humantime = "2.1.0"
regex = "1.7.1"
moka = "0.9.7"
uuid = "1.2.1"
bs58 = "0.4.0"
digest = "0.10.6"
ed25519 = "1.5.2"
ed25519-dalek = "1.0.1"
ed25519-dalek-bip32 = "0.2.0"
generic-array = "0.14.6"
secp256k1 = "0.24.2" 
strum = "0.24.1"
num-bigint = "0.4"
num-rational = "0.4.1"
tendermint = "0.28.0"
tendermint-proto = "0.28.0"
tendermint-light-client = "0.28.0"
tendermint-light-client-verifier = "0.28.0" 
serial_test = "1.0.0"
env_logger = "0.10.0"
tracing-subscriber = "0.3.14"
test-log = "0.2.10"

# Needed for generating (synthetic) light blocks.
tendermint-testgen = "0.28.0"

atty                     = "0.2.14"
clap                     = "3.2"
clap_complete            = "3.2"
color-eyre               = "0.6"
console                  = "0.15.5"
eyre                     = "0.6.8"
oneline-eyre             = "0.1"
signal-hook              = "0.3.15"
abscissa_core = "=0.6.0"
once_cell = "1.17"
rouille           = "3.6"
ureq       = "2.6.2"
ics23 = "=0.9.0"
time = ">=0.3.0, <0.3.18"
erased-serde = "0.3"
safe-regex = "0.2.5"
derive_more = "0.99.17"
uint = "0.9"
primitive-types = "0.12.1"
dyn-clone = "1.0.8"
modelator = "0.4.2"
dialoguer = "0.10.3"
opentelemetry            = "0.18.0"
opentelemetry-prometheus = "0.11.0"
prometheus               = "0.13.2"
dashmap                  = "5.4.0"
lazy_static     = "1.4.0"
mdbook-template = "1.1.0"
walkdir         = "2.3.2"
tempfile = "3.3.0"
rand = "0.8.5"
serde_yaml = "0.9.16"