[workspace]

members = [
    "modules",
    "relayer",
    "relayer-cli",
    "proto"
]

exclude = [
    "proto-compiler"
]

[patch.crates-io]

tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", branch = "rpc/tx_search" }
tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", branch = "rpc/tx_search" }
tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "rpc/tx_search" }
tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", branch = "rpc/tx_search" }