[package]
name         = "ibc-relayer-types"
version      = "0.22.0"
edition.workspace = true
license.workspace = true
readme       = "README.md"
keywords     = ["blockchain", "consensus", "cosmos", "ibc", "tendermint"]
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description  = """
    Implementation of the Inter-Blockchain Communication Protocol (IBC).
    This crate comprises the main data structures and on-chain logic.
"""

[package.metadata.docs.rs]
all-features = true

[features]
default = ["std"]
std = ["flex-error/std", "flex-error/eyre_tracer", "ibc-proto/std", "clock"]
clock = ["tendermint/clock", "time/std"]

# This feature grants access to development-time mocking libraries, such as `MockContext` or `MockHeader`.
# Depends on the `testgen` suite for generating Tendermint light blocks.
mocks = ["tendermint-testgen", "clock", "std"]

[dependencies]
# Proto definitions for all IBC-related interfaces, e.g., connections or channels.
ibc-proto = { workspace = true, default-features = false }
ics23 = { workspace = true, default-features = false, features = ["host-functions"] }
time = { workspace = true, default-features = false }
serde_derive = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false }
serde_json = { workspace = true, default-features = false }
erased-serde = { workspace = true, default-features = false, features = ["alloc"] }
prost = { workspace = true, default-features = false }
bytes = { workspace = true, default-features = false }
safe-regex = { workspace = true, default-features = false }
subtle-encoding = { workspace = true, default-features = false }
flex-error = { workspace = true, default-features = false }
derive_more = { workspace = true, default-features = false, features = ["from", "into", "display"] }
uint = { workspace = true, default-features = false }
itertools = { workspace = true, default-features = false, features = ["use_alloc"] }
primitive-types = { workspace = true, default-features = false, features = ["serde_no_std"] }
dyn-clone.workspace = true
num-rational.workspace = true

[dependencies.tendermint]
workspace = true
default-features = false

[dependencies.tendermint-proto]
workspace = true
default-features = false

# Temporary, until this change makes it into a tendermint-rs release:
# https://github.com/informalsystems/tendermint-rs/pull/1204
[dependencies.tendermint-rpc]
workspace = true
default-features = false

[dependencies.tendermint-light-client-verifier]
workspace = true
default-features = false

[dependencies.tendermint-testgen]
workspace = true
optional = true
default-features = false

[dev-dependencies]
env_logger.workspace = true
tracing = { workspace = true, default-features = false }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "json"]}
test-log = { workspace = true, features = ["trace"] }
modelator.workspace = true
tendermint-rpc = { workspace = true, features = ["http-client", "websocket-client"] }
tendermint-testgen = { workspace = true } # Needed for generating (synthetic) light blocks.
