[package]
name       = "ibc-proto"
version    = "0.11.0"
authors    = ["Informal Systems <hello@informal.systems>"]
edition    = "2018"
license    = "Apache-2.0"
repository = "https://github.com/informalsystems/ibc-rs/tree/master/proto"
readme     = "README.md"
categories = ["cryptography", "cryptography::cryptocurrencies", "database"]
keywords   = ["blockchain", "cosmos", "tendermint", "ibc", "proto"]
exclude    = ["definitions"]

description = """
    ibc-proto is a Rust implementation of the Cosmos SDK & IBC proto structs.
    """

[lib]
name = "ibc_proto"
path = "src/lib.rs"

[package.metadata.docs.rs]
all-features = true

[dependencies]
prost = { package = "informalsystems-prost", version = "0.8.1", default-features = false }
prost-types = { package = "informalsystems-prost-types", version = "0.8.1", default-features = false }
bytes = { version = "1.1", default-features = false }
tonic = { package = "informalsystems-tonic", version = "0.5.2", optional = true }

[dependencies.tendermint-proto]
version = "=0.22.0"
default-features = false

[features]
default = ["std"]
std = ["tonic"]
