[package]
name         = "ibc-telemetry"
version      = "0.22.0"
edition.workspace = true
license.workspace = true
readme       = "README.md"
keywords     = ["cosmos", "ibc", "relayer", "telemetry"]
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description  = """
    Telemetry service for the Hermes IBC relayer
"""

[dependencies]
ibc-relayer-types = { version = "0.22.0", path = "../relayer-types" }

once_cell.workspace = true
opentelemetry            = { workspace = true, features = ["metrics"] }
opentelemetry-prometheus.workspace = true
prometheus.workspace = true
rouille.workspace = true
moka.workspace = true
dashmap.workspace = true
serde_json.workspace = true
serde.workspace = true

[dependencies.tendermint]
workspace = true
default-features = false
